### ISSUE TITLE
ENH: Create a package with the minimal dependencies

### ISSUE THREAD

**Issue by fcollonval** [conda-forge/fmpy-feedstock#11]
This is an enhancement proposal.

With `pip` it is possible to choose the dependency granularity (and it is beautifully illustrated by this project). Unfortunately with `conda` this can only be done through different packages. 
`matplotlib` recipe solves this nicely by outputting various package from an [unique recipe](https://github.com/conda-forge/matplotlib-feedstock/blob/6216392f740e955fd5eb12cf3c2068d482c5e9c2/recipe/meta.yaml#L72-L84). It makes sense to keep the current `fmpy` package with all dependencies. But it would be great to generate at the same time a `fmpy-base` (name to be chosen) for advanced users with the minimal dependencies.

Note: if you agree, I happily submit a PR.

**Comment by t-sommer** [comment]
AFAIK pip also supports permutations of optional dependencies, e.g. `examples` and `plot` but no `gui`. Is this also possible with conda?

**Comment by fcollonval** [comment]
Unfortunately `conda` lacks behind on that front 😞 This is the reason restricting to two flavors seems a good strategy to me: 
* one shipping all dependencies for easy usage (with the direct package name) and 
* one restricting to the minimal set for advanced user

Note: matplotlib went for `matplotlib` and `matplotlib-base`

conda build doc: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section

**Comment by t-sommer** [comment]
Can't you just install with `--no-deps` and select the dependencies you need?

**Comment by fcollonval** [comment]
Sorry for the late answer. 

I try using `--no-deps`. It works as expected. But unfortunately, each time I made a modification (install, remove or update a package) on the environment, `conda` is installing all `fmpy` dependencies to correct the inconsistency. So back to my proposal to have a `fmpy-base` package with minimal dependencies. What do you think?

**Comment by trulede** [comment]
I have a similar problem/idea. I'm looking into creating a sub-package called `FMPy.fmi `which includes the FMI interface code and loaders. Basically a separate` setup.py `under `fmpy/fmi` but still in the same git repo ... so its mostly seamless. Then you could:

- `pip install FMPy `(depends on FMPy.fmi) and get everything.
- `pip install FMPy.fmi `and only get those "core" FMI related packages and dependencies.

So I think its an approach which might help in other areas too.

**Comment by t-sommer** [comment]
I've started a new attempt on https://github.com/conda-forge/fmpy-feedstock/tree/testing but found a number of issues:

- the conda package is deployed with label `main` (instead of `testing`) to the conda-forge channel even though a `recipe/conda_build_config.yaml` has been added:

```yaml
channel_targets:
  - conda-forge testing
```

- `pyqt >=5.12.3,<5.13.0a0` is listed in the `index.json` as a dependency for `fmpy-base` even though it is only a `build` dependency

- the `fmpy` entry point does not work with `fmpy-base`:

```
(fmpybase) C:\Users\XXX\Documents>fmpy info Clock.fmu
Fatal error in launcher: Unable to create process using '"d:\bld\fmpy_1602599620764\_h_env\python.exe"  "E:\Anaconda3\envs\fmpybase\Scripts\fmpy.exe" info Clock1.fmu': Das System kann die angegebene Datei nicht finden.
```

however it _does_ work after installing `fmpy`.

**Comment by t-sommer** [comment]
@fcollonval, @wulmer, do you have an idea how to fix the above points?

**Comment by t-sommer** [comment]
It turns out that we have to run `conda smithy rerender` after making changes to the meta.yaml. This solved the problem with the `testing` label.
